image: "node:lts-alpine"

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

.netlify:
  stage: deploy
  image:
    name: "ghcr.io/williamjacksn/netlify-cli:12.2.9"
    entrypoint: [""]
  needs:
    - build

netlify:preview:
  extends: .netlify
  script:
    - netlify deploy --dir public
  rules:
    - if: $CI_MERGE_REQUEST_ID

netlify:production:
  extends: .netlify
  script:
    - netlify deploy --dir public --prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
